jQuery(function(){jQuery(".listborder").append('<div class="cl"></div>');jQuery('.hireUL li a').css({background:'url(/images_cand/tj_images/home/hiring_logo.gif) no-repeat 0 0'});jQuery('.smUL li a').css({background:'url(/images_cand/tj_images/home/sm_hire.gif) no-repeat 0 0'});jQuery('.cbi_logo li a').css({background:'url(/images_cand/tj_images/home/cbi_logo.gif) no-repeat 0 0'});var countList=jQuery('.hireUL li').length;var topPos=0+"px";var leftPos=0+"px";var count=0;for(row=0;row<(countList/3);row++){topPos=-(50*row)+"px";for(col=0;col<3;col++){leftPos=-(111*col)+"px";jQuery('.hireUL li').eq(count).find('a').css({backgroundPosition:""+leftPos+" "+topPos+""});if(col==2){jQuery('.hireUL li').eq(count).css({margin:"0"})};count++;}}
var sm_countList=jQuery('.smUL li').length;topPos=0+"px";leftPos=0+"px";count=0;for(row=0;row<(sm_countList/4);row++){topPos=-(50*row)+"px";for(col=0;col<4;col++){leftPos=-(78*col)+"px";jQuery(".smUL li").eq(count).find('a').css({backgroundPosition:""+leftPos+" "+topPos+""});count++;}}
var countList=jQuery('.cbi_logo li').length;var topPos=0+"px";var leftPos=0+"px";var count=0;for(row=0;row<(countList/3);row++){topPos=-(50*row)+"px";for(col=0;col<3;col++){leftPos=-(111*col)+"px";jQuery('.cbi_logo li').eq(count).find('a').css({backgroundPosition:""+leftPos+" "+topPos+""});if(col==2){jQuery('.cbi_logo li').eq(count).css({margin:"0"})};count++;}}
jQuery.getJSON("/newtj_js/scripts/data.json",function(data){jQuery('.tipLst li').hover(function(){var li_num=jQuery(this).index();if(jQuery(this).parent().attr("id")=='hiring'){if(data.hiring[li_num].company!=undefined){jQuery(this).append('<span class="tip"><span class="spanTip"><img src="/images_cand/tj_images/home/blueTip.gif" class="bTip" /></span></span>');jQuery(this).find('.spanTip').append("<b>"+data.hiring[li_num].company+"</b>");}
if(data.hiring[li_num].industry!=undefined){jQuery(this).find('.spanTip').append("<br/><span>Industry: "+data.hiring[li_num].industry+"</span>");}
if(data.hiring[li_num].id!=undefined){var id=data.hiring[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.spanTip').append('<br/><a href="#" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');}}
jQuery(this).find('a').attr({"href":""+data.hiring[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='hotEmp'){if(data.hotEmp[li_num].company!=undefined){jQuery(this).append('<span class="tip"><span class="spanTip"><img src="/images_cand/tj_images/home/blueTip.gif" class="bTip" /></span></span>');jQuery(this).find('.spanTip').append("<b>"+data.hotEmp[li_num].company+"</b>");}
if(data.hotEmp[li_num].industry!=undefined){jQuery(this).find('.spanTip').append("<br/><span>Industry: "+data.hotEmp[li_num].industry+"</span>");}
if(data.hotEmp[li_num].id!=undefined){var id=data.hotEmp[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.spanTip').append('<br/><a href="#" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');}}
jQuery(this).find('a').attr({"href":""+data.hotEmp[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='career'){if(data.career[li_num].company!=undefined){jQuery(this).append('<span class="tip"><span class="spanTip"><img src="/images_cand/tj_images/home/blueTip.gif" class="bTip" /></span></span>');jQuery(this).find('.spanTip').append("<b>"+data.career[li_num].company+"</b>");}
if(data.career[li_num].industry!=undefined){jQuery(this).find('.spanTip').append("<br/><span>Industry: "+data.career[li_num].industry+"</span>");}
jQuery(this).find('a').attr({"href":""+data.career[li_num].href+""});}
var link=jQuery(this).find('a').attr('href');var id=jQuery(this).find('a').attr('id');if(id!=undefined){var count=result[id];if(count!=undefined&&parseInt(count)>'0'){if(jQuery("#"+id+"_msg")!=null)
jQuery("#"+id+"_msg").html(count+" Job(s) Found");}}
jQuery(this).find('.spanTip a').attr({href:link});jQuery(this).css({position:'relative'}).find('.tip').show();},function(){jQuery(this).css({position:''});jQuery(this).find('.tip').remove();});});jQuery.getJSON("/newtj_js/scripts/data.json",function(data){jQuery('#featured li').hover(function(){var li_num=jQuery(this).index();var bool=false;if(jQuery(this).parent().attr("id")=='auto'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.auto[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.auto[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.auto[li_num].id!=undefined){var id=data.auto[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.auto[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='archi'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.archi[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.archi[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.archi[li_num].id!=undefined){var id=data.archi[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.archi[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='bank'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.bank[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.bank[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.bank[li_num].id!=undefined){var id=data.bank[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.bank[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='bpo'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.bpo[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.bpo[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.bpo[li_num].id!=undefined){var id=data.bpo[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.bpo[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='cdf'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.cdf[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.cdf[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.cdf[li_num].id!=undefined){var id=data.cdf[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.cdf[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='edu'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.edu[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.edu[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.edu[li_num].id!=undefined){var id=data.edu[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.edu[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='elec'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.elec[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.elec[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.elec[li_num].id!=undefined){var id=data.elec[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.elec[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='call'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.call[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.call[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.call[li_num].id!=undefined){var id=data.call[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.call[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='heal'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.heal[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.heal[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.heal[li_num].id!=undefined){var id=data.heal[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.heal[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='hosp'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.hosp[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.hosp[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.hosp[li_num].id!=undefined){var id=data.hosp[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.hosp[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='it'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.it[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.it[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.it[li_num].id!=undefined){var id=data.it[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.it[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='logi'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.logi[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.logi[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.logi[li_num].id!=undefined){var id=data.logi[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.logi[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='real'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.real[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.real[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.real[li_num].id!=undefined){var id=data.real[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.real[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='rec'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.rec[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.rec[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.rec[li_num].id!=undefined){var id=data.rec[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.rec[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='retail'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.retail[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.retail[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.retail[li_num].id!=undefined){var id=data.retail[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.retail[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='manu'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.manu[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.manu[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.manu[li_num].id!=undefined){var id=data.manu[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.manu[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='media'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.media[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.media[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.media[li_num].id!=undefined){var id=data.media[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.media[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='text'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.text[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.text[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.text[li_num].id!=undefined){var id=data.text[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.text[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='tele'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.tele[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.tele[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.tele[li_num].id!=undefined){var id=data.tele[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.tele[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='oth'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.oth[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.oth[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.oth[li_num].id!=undefined){var id=data.oth[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.oth[li_num].href+""});}
if(jQuery(this).parent().attr("id")=='pow'){jQuery(this).append('<span class="fSpanBlk"><span class="fTipBlk"><img alt="" class="fTip" src="/images_cand/tj_images/home/blueTip_ver.gif" /></span></span>');if(data.pow[li_num].logo!=undefined){jQuery(this).find('.fTipBlk').append('<img src="/images_cand/logos/featured/mouseOverlogos/'+data.pow[li_num].logo+'" class="featuredLogo"  /><br/>');bool=true;}
if(data.pow[li_num].id!=undefined){var id=data.pow[li_num].id;var count=result[id];if(count!=undefined&&parseInt(count)>'0'){jQuery(this).find('.fTipBlk').append('<a href="#" class="vwJobs" target="_blank">'+count+' Jobs <img src="/images_cand/tj_images/home/arrow_lyer.gif" alt="" width="6" height="11" border="0" align="absmiddle" /></a>');bool=true;}}
jQuery(this).find('a').attr({"href":""+data.pow[li_num].href+""});}
jQuery(this).addClass('posrel').find('.fSpanBlk').show();if(bool!=true){jQuery(this).find('.fSpanBlk').remove();}},function(){jQuery(this).find('.fSpanBlk').remove();jQuery(this).removeClass('posrel');});});if(jQuery(".mainNav ")!=null&&jQuery(".mainNav ").offset()!=null&&jQuery(".mainNav ").offset().top!=null){var scrollHeight=jQuery(".mainNav ").offset().top+90;jQuery(".contentBlk").scroll(function(e){if(jQuery(this).scrollTop()<scrollHeight){jQuery(".footBand").slideUp("slow");}else{jQuery(".footBand").slideDown("slow");}
if(jQuery(this).scrollTop()>scrollHeight){jQuery(".footBand").slideDown("slow");}});}
jQuery('.allBtn').click(function(){jQuery('.jobsList').slideToggle("fast");});jQuery('.listborder').click(function(){jQuery('.jobsList').hide();});jQuery('.edit').click(function(){jQuery('.editBlk').removeClass('posrel');jQuery(this).parents('.editBlk').addClass('posrel');jQuery('.ltBox').hide().prev('.edit').show();jQuery(this).hide().next('.ltBox').show().find('.inpt').focus();});jQuery('.cls').click(function(){jQuery(this).parents('.ltBox').hide().prev('.edit').show();jQuery(this).parents('.editBlk').removeClass('posrel');jQuery('.err').html('');jQuery('.green').html('');jQuery('.green').removeClass('green').addClass('err');jQuery('.err').hide();});jQuery('.resume').click(function(){jQuery(this).parent().addClass('posrel')
jQuery('.ltBox').hide().prev('.edit').show();jQuery(this).next('.ltBox').show();});jQuery('.errCls').click(function(){jQuery(this).parents('.loginErr').hide();});jQuery('.defaultValue').each(function(){var defaultValue=this.value;jQuery(this).css('color','#B3B3B3');jQuery(this).focus(function(){if(this.value==defaultValue){this.value='';jQuery(this).css('color','#333');}});jQuery(this).blur(function(){if(this.value==''){jQuery(this).css('color','#B3B3B3');this.value=defaultValue;}});});jQuery('#txtKeywordsId').focus(function(){jQuery('.alertHide').slideDown();});});